/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as AuthenticatedSpendingRouteImport } from './routes/_authenticated/spending'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScenariosRouteImport } from './routes/_authenticated/scenarios'
import { Route as AuthenticatedRetirementRouteImport } from './routes/_authenticated/retirement'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedAssumptionsRouteImport } from './routes/_authenticated/assumptions'
import { Route as AuthenticatedScenariosIndexRouteImport } from './routes/_authenticated/scenarios.index'
import { Route as AuthenticatedScenariosScenarioIdRouteImport } from './routes/_authenticated/scenarios.$scenarioId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSpendingRoute = AuthenticatedSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScenariosRoute = AuthenticatedScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetirementRoute = AuthenticatedRetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssumptionsRoute =
  AuthenticatedAssumptionsRouteImport.update({
    id: '/assumptions',
    path: '/assumptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScenariosIndexRoute =
  AuthenticatedScenariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedScenariosRoute,
  } as any)
const AuthenticatedScenariosScenarioIdRoute =
  AuthenticatedScenariosScenarioIdRouteImport.update({
    id: '/$scenarioId',
    path: '/$scenarioId',
    getParentRoute: () => AuthenticatedScenariosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assumptions': typeof AuthenticatedAssumptionsRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/retirement': typeof AuthenticatedRetirementRoute
  '/scenarios': typeof AuthenticatedScenariosRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/spending': typeof AuthenticatedSpendingRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/scenarios/$scenarioId': typeof AuthenticatedScenariosScenarioIdRoute
  '/scenarios/': typeof AuthenticatedScenariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assumptions': typeof AuthenticatedAssumptionsRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/retirement': typeof AuthenticatedRetirementRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spending': typeof AuthenticatedSpendingRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/scenarios/$scenarioId': typeof AuthenticatedScenariosScenarioIdRoute
  '/scenarios': typeof AuthenticatedScenariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assumptions': typeof AuthenticatedAssumptionsRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/retirement': typeof AuthenticatedRetirementRoute
  '/_authenticated/scenarios': typeof AuthenticatedScenariosRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/spending': typeof AuthenticatedSpendingRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/_authenticated/scenarios/$scenarioId': typeof AuthenticatedScenariosScenarioIdRoute
  '/_authenticated/scenarios/': typeof AuthenticatedScenariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assumptions'
    | '/coach'
    | '/dashboard'
    | '/portfolio'
    | '/retirement'
    | '/scenarios'
    | '/settings'
    | '/spending'
    | '/api/healthz'
    | '/scenarios/$scenarioId'
    | '/scenarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assumptions'
    | '/coach'
    | '/dashboard'
    | '/portfolio'
    | '/retirement'
    | '/settings'
    | '/spending'
    | '/api/healthz'
    | '/scenarios/$scenarioId'
    | '/scenarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assumptions'
    | '/_authenticated/coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/portfolio'
    | '/_authenticated/retirement'
    | '/_authenticated/scenarios'
    | '/_authenticated/settings'
    | '/_authenticated/spending'
    | '/api/healthz'
    | '/_authenticated/scenarios/$scenarioId'
    | '/_authenticated/scenarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/spending': {
      id: '/_authenticated/spending'
      path: '/spending'
      fullPath: '/spending'
      preLoaderRoute: typeof AuthenticatedSpendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenarios': {
      id: '/_authenticated/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof AuthenticatedScenariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retirement': {
      id: '/_authenticated/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof AuthenticatedRetirementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assumptions': {
      id: '/_authenticated/assumptions'
      path: '/assumptions'
      fullPath: '/assumptions'
      preLoaderRoute: typeof AuthenticatedAssumptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenarios/': {
      id: '/_authenticated/scenarios/'
      path: '/'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof AuthenticatedScenariosIndexRouteImport
      parentRoute: typeof AuthenticatedScenariosRoute
    }
    '/_authenticated/scenarios/$scenarioId': {
      id: '/_authenticated/scenarios/$scenarioId'
      path: '/$scenarioId'
      fullPath: '/scenarios/$scenarioId'
      preLoaderRoute: typeof AuthenticatedScenariosScenarioIdRouteImport
      parentRoute: typeof AuthenticatedScenariosRoute
    }
  }
}

interface AuthenticatedScenariosRouteChildren {
  AuthenticatedScenariosScenarioIdRoute: typeof AuthenticatedScenariosScenarioIdRoute
  AuthenticatedScenariosIndexRoute: typeof AuthenticatedScenariosIndexRoute
}

const AuthenticatedScenariosRouteChildren: AuthenticatedScenariosRouteChildren =
  {
    AuthenticatedScenariosScenarioIdRoute:
      AuthenticatedScenariosScenarioIdRoute,
    AuthenticatedScenariosIndexRoute: AuthenticatedScenariosIndexRoute,
  }

const AuthenticatedScenariosRouteWithChildren =
  AuthenticatedScenariosRoute._addFileChildren(
    AuthenticatedScenariosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssumptionsRoute: typeof AuthenticatedAssumptionsRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedRetirementRoute: typeof AuthenticatedRetirementRoute
  AuthenticatedScenariosRoute: typeof AuthenticatedScenariosRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSpendingRoute: typeof AuthenticatedSpendingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssumptionsRoute: AuthenticatedAssumptionsRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedRetirementRoute: AuthenticatedRetirementRoute,
  AuthenticatedScenariosRoute: AuthenticatedScenariosRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSpendingRoute: AuthenticatedSpendingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiHealthzRoute: ApiHealthzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
